services:
    database:
        image: postgres:latest
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        volumes:
            - database:/var/lib/postgresql/data
    fily:
        image: ghcr.io/fritsstegmann/lary:main
        ports:
            - 8333:8333
        volumes:
            - fily:/data
volumes:
    database:
    fily:
