
services:
   database:
      image: postgres:latest
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         PGDATA: /var/lib/postgresql/data/pgdata
      ports:
        - 5432:5432
      volumes:
         - database:/var/lib/postgresql/data
volumes:
    database:
